services:
  web:
    build: .
    ports: 
      - "8080:8080"
    volumes:
      - .:/app
    
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    
volumes:
  data: